name: Terraform Import Secrets (DEV)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  import:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TFSTATE_BUCKET: "tfstate-bootstrap-project-487710"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Authenticate to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA }}

      - name: Terraform init (dev)
        run: |
          terraform -chdir=terraform/gcp/env/dev init \
            -backend-config="bucket=${TFSTATE_BUCKET}" \
            -backend-config="prefix=gcp/env/dev"

      - name: Terraform import secrets (dev)
        run: |
          cd terraform/gcp/env/dev

          terraform import 'google_secret_manager_secret.snowflake["account"]'   'projects/snowdbt-dev/secrets/snowflake-account-dev'   || true
          terraform import 'google_secret_manager_secret.snowflake["user"]'      'projects/snowdbt-dev/secrets/snowflake-user-dev'      || true
          terraform import 'google_secret_manager_secret.snowflake["password"]'  'projects/snowdbt-dev/secrets/snowflake-password-dev'  || true
          terraform import 'google_secret_manager_secret.snowflake["role"]'      'projects/snowdbt-dev/secrets/snowflake-role-dev'      || true
          terraform import 'google_secret_manager_secret.snowflake["warehouse"]' 'projects/snowdbt-dev/secrets/snowflake-warehouse-dev' || true
          terraform import 'google_secret_manager_secret.snowflake["database"]'  'projects/snowdbt-dev/secrets/snowflake-database-dev'  || true
          terraform import 'google_secret_manager_secret.snowflake["schema"]'    'projects/snowdbt-dev/secrets/snowflake-schema-dev'    || true

      - name: Terraform plan (dev)
        run: terraform -chdir=terraform/gcp/env/dev plan